AWSTemplateFormatVersion: '2010-09-09'
Description: Builds a CI/CD Pipeline to deploy a configurable RabbitMQ (Across Multiple Accounts)

Parameters:
# Product Parameters
  pProduct:
    Type: String
    Description: Product Name
    Default: ""
  pTeam:
    Type: String
    Description: Team Name
    Default: "teamA"

### Pipeline Configuration: 

  pBranchName:
    Type: String
    Description: Branch Name to Deploy
    Default: main

# Template Path: 
  pTemplatePath: 
    Type: String
    Default: 'app/cloudformation.yml'
    Description: Path to the template to deploy from the source or build artifact
 
# Optional Configuration File for Dev
  pConfigurationPathDev: 
    Type: String
    Default: 'app/config/configuration-dev.json'
    Description: (Optional) CloudFormation Configuration file for Dev
  
  pDevAccountNumber:
    Type: String
    Default: '707017293678'
  pRegion1Name:
    Type: String
    Default: 'us-east-1'

Resources:

  rS3KMSKey:
    Type: AWS::KMS::Key
    Properties:
      KeyPolicy:
        Version: 2012-10-17
        Id: key-s3
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
  
  rS3KMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/rabbit-storage-key
      TargetKeyId: !Ref rS3KMSKey

  rS3RabbitStorageBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            KMSMasterKeyID: !Sub 'arn:aws:kms:${AWS::Region}:${AWS::AccountId}:${rS3KMSKeyAlias}'
            SSEAlgorithm: 'aws:kms'

  rCodePipelineRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
                - cloudformation.amazonaws.com
                - codebuild.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'

  rCodeRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: RabbitRepo
      # Triggers:
      #   - Name: DefaultTrigger
      #     Branches:
      #     - development
      #     DestinationArn: !Sub arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${pProduct}-${pTeam}-${pBranchName}
      #     Events:
      #     - all

  # ------------
  # CodeBuild
  # ------------
  # rScanCodeBuildProject:
  #   Type: AWS::CodeBuild::Project
  #   Properties:
  #     Name: !Sub ${pProduct}-template-scan-${pBranchName}
  #     Description: CodeBuild Stage to Scan Created Templates
  #     ServiceRole: !Ref pCodeBuildRole
  #     Artifacts:
  #         Type: CODEPIPELINE
  #     Environment:
  #         Type: LINUX_CONTAINER
  #         ComputeType: BUILD_GENERAL1_SMALL
  #         Image: aws/codebuild/standard:5.0
  #         PrivilegedMode: true  
  #     Source:
  #       Type: CODEPIPELINE
  #       BuildSpec: 'cicd/scan_buildspec.yml'
  #     TimeoutInMinutes: 10
  #     # EncryptionKey: !Ref rS3KMSKey

  rCodeBuildLambdaCodeProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${pProduct}-build-LambdaCode-${pBranchName}
      Description: This project will be used for Deploying the Lambda Code for RabbitMQ
      ServiceRole: !Ref rCodePipelineRole
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: CODE_BUCKET_R1
            Value: !Ref rS3RabbitStorageBucket
          - Name: BUCKET_PREFIX
            Value: !Ref pProduct
          - Name: KMS_ARN_R1
            Value: !Ref rS3KMSKey
      Source:
        Type: CODEPIPELINE
        BuildSpec: cicd/lambdabuildspec.yml
      TimeoutInMinutes: 10
      # EncryptionKey: !Ref rS3KMSKey
      ResourceAccessRole: !Ref rCodePipelineRole
  # --------------
  # CodePipeline
  # --------------
  rCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RestartExecutionOnUpdate: True
      ArtifactStores:
        - Region: !Ref pRegion1Name
          ArtifactStore:
            EncryptionKey:
              Id: !Ref rS3KMSKey
              Type: KMS
            Location: !Ref rS3RabbitStorageBucket
            Type: S3
      Name: !Sub ${pProduct}-${pTeam}-${pBranchName}
      RoleArn: !Sub ${rCodePipelineRole.Arn}
      Stages:
        - Name: Source
          Actions:
            - Name: TemplateSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: "1"
              Configuration:
                BranchName: !Ref pBranchName
                RepositoryName: !Sub ${rCodeRepo.Name}
                PollForSourceChanges: false
              OutputArtifacts:
                - Name: Source
              RunOrder: 1
        - Name: BuildAndPackage
          Actions:
            - Name: CodeBuild-ZipUploadCode
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName: !Ref rCodeBuildLambdaCodeProject
              InputArtifacts:
                - Name: Source
              OutputArtifacts:
                - Name: Build-LambdaCode
              RunOrder: 2
            
            # - Name: Scan_CodeBuild_Project
            #   ActionTypeId:
            #     Category: Build
            #     Owner: AWS
            #     Provider: CodeBuild
            #     Version: "1"
            #   Configuration:
            #     ProjectName: !Ref rScanCodeBuildProject
            #   InputArtifacts:
            #     - Name: Source
            #   OutputArtifacts:
            #     - Name: Scan-Build
            #   RunOrder: 1
        - Name: !Sub ${pTeam}-Dev
          Actions:
            - Name: !Sub Deploy_Dev-${pRegion1Name}
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              Configuration:
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                RoleArn: !Sub arn:aws:iam::${pDevAccountNumber}:role/${rCodePipelineRole}
                StackName: !Sub ${pProduct}-${pTeam}
                ParameterOverrides: !Sub |
                  {
                    "pLambdaCodeBucket": "${rS3RabbitStorageBucket}",
                    "pObjectVersion": {"Fn::GetParam":["Build-LambdaCode","output.json","oObjectVersionR1"]}
                  }
                TemplatePath: !Sub Source::${pTemplatePath}
                TemplateConfiguration: !Sub Source::${pConfigurationPathDev}
                OutputFileName: Outputs-Dev-R1.json
              InputArtifacts:
                - Name: Source
                - Name: Build-LambdaCode
              OutputArtifacts:
                - Name: Outputs-Dev-R1
              RoleArn: !Sub arn:aws:iam::${pDevAccountNumber}:role/${rCodePipelineRole}
              Region: !Ref pRegion1Name
              RunOrder: 1

  # # -------------------------------------------
  # # CloudWatch Event
  # # -------------------------------------------
  # rInitiatePipelineEvent:
  #   Type: AWS::Events::Rule
  #   Properties:
  #     Description: 'Amazon CloudWatch Events rule to automatically start your pipeline when a change occurs to a CodeCommit Repository'
  #     EventPattern:
  #       source:
  #         - aws.codecommit
  #       detail-type:
  #         - "CodeCommit Repository State Change"
  #       resources:
  #         - !Sub arn:aws:codecommit:${pRegion1Name}:${AWS::AccountId}:${pProduct}
  #       detail:
  #         referenceType:
  #           - branch
  #         referenceName:
  #           - !Ref pBranchName
  #     Name: !Sub ${pProduct}-${pTeam}-f-${pBranchName}
  #     State: "ENABLED"
  #     Targets:
  #       - RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/CodePipeline-Service
  #         Arn: !Sub arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${rCodePipeline}
  #         Id: !Sub "${pProduct}_Initial_CodePipeline_V1"   