  version: 0.2
  phases:
    install:
      runtime-versions:
          python: 3.11
    install:
      commands:
        - apt-get install -y jq
    build:
      commands:
        - echo $(pwd)
        - cd RabbitLambda
        - zip -r RabbitLambda.zip *
        - ls -ltr
        - pwd
        - mv RabbitLambda.zip ../
        - cd ..
        - pwd
        - ls -ltr
        
        - aws s3 cp RabbitLambda.zip s3://$CODE_BUCKET_R1/$BUCKET_PREFIX/RabbitLambda.zip
        - objVersionr1=$(aws s3api list-object-versions --bucket $CODE_BUCKET_R1 --prefix $BUCKET_PREFIX/RabbitLambda.zip | jq ".Versions[0].VersionId")
        - echo "Uploaded Zipped Code to Lambda Bucket - $CODE_BUCKET_R1"

        # - aws s3 cp RabbitLambda.zip s3://$CODE_BUCKET_R2/$BUCKET_PREFIX/RabbitLambda.zip --sse aws:kms --sse-kms-key-id $KMS_ARN_R2 --region us-west-2
        # - objVersionr2=$(aws s3api list-object-versions --bucket $CODE_BUCKET_R2 --prefix $BUCKET_PREFIX/RabbitLambda.zip | jq ".Versions[0].VersionId")
        # - echo "Uploaded Zipped Code to Lambda Bucket - $CODE_BUCKET_R2"

        #- echo "{\"oObjectVersionR1\":"$objVersionr1",\"oObjectVersionR2\":"$objVersionr2"}" | jq . > output.json
        - echo "{\"oObjectVersionR1\":"$objVersionr1"}" | jq . > output.json
        - ls -ltr
        - pwd
        - cat output.json
  artifacts:
    files:
      - output.json