  version: 0.2
  phases:
    install:
      runtime-versions:
          python: 3.9
      commands:
        - apt-get install -y jq
    build:
      commands:
        - echo $(pwd)
        - cd RabbitLambda
        - zip -r RabbitLambda.zip *
        - ls -ltr
        - pwd
        - mv RabbitLambda.zip ../
        - cd ..
        - pwd
        - ls -ltr
        
        - aws s3 cp RabbitLambda.zip s3://$CODE_BUCKET_R1/$BUCKET_PREFIX/RabbitLambda.zip
        - objVersionr1=$(aws s3api list-object-versions --bucket $CODE_BUCKET_R1 --prefix $BUCKET_PREFIX/RabbitLambda.zip | jq ".Versions[0].VersionId")
        - echo "Uploaded Zipped Code to Lambda Bucket - $CODE_BUCKET_R1"

        # What is this section for??
        - echo "{\"oObjectVersionR1\":"$objVersionr1"}" | jq . > output.json
        - ls -ltr
        - pwd
        - cat output.json
  artifacts:
    files:
      - output.json