AWSTemplateFormatVersion: 2010-09-09
Description: Sample Template for team Simple-CloudFormation for app
Transform: 'AWS::Serverless-2016-10-31' # Remove if not using a serverless function

Parameters:
  product:
    Description: Name of the instance
    Type: String
    Default: 'is'
  env:
    Description: Environment Name
    Type: String
    Default: 'dev'

  ## Pipeline Parameters
  Region:
    Type: String
    Description: Main Region for Infrastructure
    Default: us-east-1
  Region2Active:
    Type: String
    Description: Parameter to activate R2 or not
    Default: No

  ## App Specific Parameters
  VPCId:
    Description: VPC ID
    Type: String
    Default: 'vpc-123'
  AppSubnets:
    Description: An Array of the App Subnet IDs
    Type: List<AWS::EC2::Subnet::Id>
    Default: subnet-1
  AppSubnetCIDR1:
    Description: An Array of the Intranet Subnet IDs
    Type: String
    Default: '10.0.0.0/24'
  InstanceWarmup:
    Type: String
    Description: Time in Seconds from Instance Launch Before Contributing to Scaling Metrics
    Default: 720
  InstanceType:
    Type: String
    Description: Instance size for app
    Default: c5a.large
  AutoscalingCPUTarget:
    Type: String
    Description: Target % of CPU Usage to Target for the Application ASG
    Default: 70 #(change 80 for dev )
  
  ## AmazonMQ specific Parameters
  LambdaCodeBucket:
    Type: String
    Description: S3 Bucket that contains the Lambda Code for RabbitMQ
    Default: "cf-templates--us-east-1"
  ObjectVersion:
    Type: String
    Description: S3 Version of the Lambda Code to use
    Default: "1"
  AppSubnet1:
    Type: String
    Description: AppSubnet1 ID
    Default: 'subnet-1'
  AdminUsername:
    Description: The admin username for RabbitMQ (Can't contain commas, colons, equals signs, or spaces)
    Type: String
    Default: rabbit-admin
    MinLength: 12


Conditions:
  cIsMainRegion: !Equals [!Ref AWS::Region, !Ref Region]
  cIsR2: !Not [!Condition cIsMainRegion]
  cIsR2Active: !Equals [!Ref Region2Active, "Yes"]
  cIsR2andActive: !And [!Condition cIsR2, !Condition cIsR2Active]
  cIsR2ActiveOrIsMain: !Or [!Condition cIsMainRegion, !Condition cIsR2andActive]
  cIsProd: !Equals [!Ref env, "prod"]
  cIsNonProd: !Not [!Condition cIsProd]
  cIsDev: !Equals [!Ref env, "dev"]
  cIsEitherProd: !Or [!Condition cIsPreProd, !Condition cIsProd]

Resources:
  ## Application server cluster IAM resources
  rApplicationInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${product}-role-${env}-instance-${AWS::Region}
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      #PermissionsBoundary: !Sub arn:aws:iam::${AWS::AccountId}:policy/team-fed-svcrole-boundary
      Policies:
        - PolicyName: AllowKMSAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:   
              - Sid: allowsecretaccess
                Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: 
                  - !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:ab-app-app-secret-${env}-rabbit*
              - Sid: allowkmsforsecrets
                Effect: Allow
                Action:
                  - kms:DescribeKey
                  - kms:Decrypt
                  - kms:Encrypt
                  - kms:GenerateDataKey
                Resource: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/*
                Condition:
                  ForAnyValue:StringLike:
                    kms:ResourceAliases:
                      - !Sub alias/${product}-rabbit-user-pwd-key
              - Sid: allowkmsfordepls3
                Effect: Allow
                Action:
                  - kms:DescribeKey
                  - kms:Decrypt
                  - kms:Encrypt
                  - kms:GenerateDataKey
                Resource: '*'

  rApplicationInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref rApplicationInstanceRole

  rApplicationSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${product}-secgroup-${env}-instances
      VpcId: !Ref VPCId
      GroupDescription: Enable Outbound Internet and Console NLB Ingress Access to Application Instances
      SecurityGroupIngress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 127.0.0.1/32
          Description: Default local host all traffic
      SecurityGroupEgress:
        ##RabbitMQ
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          DestinationSecurityGroupId: !Ref rRabbitMQClusterSecurityGroup
          Description: Egress to Amazon MQ for Rabbit MQ
        - IpProtocol: tcp
          FromPort: 5671
          ToPort: 5671
          DestinationSecurityGroupId: !Ref rRabbitMQClusterSecurityGroup
          Description: Egress to Amazon MQ for Rabbit MQ  
        - IpProtocol: tcp
          FromPort: 5671
          ToPort: 5671
          CidrIp: '10.0.0.0/24' #!Ref pMQcidr1
          Description: Egress to IntraSubnet1 for Rabbit MQ Custom DNS


  rApplicationInstanceASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub ${product}-asg-${env}-instances-1
      MinSize:
        !If
          - cIsR2ActiveOrIsMain
          - !If
            - cIsDev
            - 1 #!Ref pDevInstanceCount
            - 1 #!Ref pInstanceCount
          - '0'
      MaxSize: 
        !If 
          - cIsR2ActiveOrIsMain
          - !If
            - cIsDev
            - 1 #!Ref pDevMaxInstanceCount
            - 1 #!Ref pMaxInstanceCount
          - '0'
      DesiredCapacity: 
        !If 
          - cIsR2ActiveOrIsMain
          - !If
            - cIsDev
            - 1 #!Ref pDevInstanceCount
            - 1 #!Ref pInstanceCount
          - '0'

      HealthCheckGracePeriod: 300
      NewInstancesProtectedFromScaleIn: false
      LaunchTemplate:
        LaunchTemplateId: !Ref rApplicationLaunchTemplate
        Version: !GetAtt rApplicationLaunchTemplate.LatestVersionNumber
      VPCZoneIdentifier: !Ref AppSubnets
      MetricsCollection:
        - Granularity: "1Minute"
          Metrics:
            - "GroupMinSize"
            - "GroupMaxSize"

  rApplicationASGScalingPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties: 
      AutoScalingGroupName: !Ref rApplicationInstanceASG
      EstimatedInstanceWarmup: !Ref InstanceWarmup
      # MetricAggregationType: Average
      PolicyType: TargetTrackingScaling
      TargetTrackingConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ASGAverageCPUUtilization
        TargetValue: !Ref AutoscalingCPUTarget

  rApplicationLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub ${product}-launchtemp-${env}-instances
      LaunchTemplateData:
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              DeleteOnTermination: true
              Encrypted: true
              VolumeSize: !If [cIsNonProd, 50, 100]
              VolumeType: gp3
          - DeviceName: /dev/xvdf # /dev/sdf
            Ebs:
              DeleteOnTermination: true
              Encrypted: true
              VolumeSize: !If [cIsNonProd, 150, 200]
              VolumeType: sc1
        IamInstanceProfile:
          Name: !Ref rApplicationInstanceProfile
        ImageId: ami-7 #ami-6
        InstanceType: !Ref InstanceType #c5a.large
        MetadataOptions:
          HttpEndpoint: enabled
          HttpPutResponseHopLimit: 2
          HttpTokens: required
        Monitoring:
          Enabled: true
        SecurityGroupIds:
          - !Ref rApplicationSecurityGroup

  ### AmazonMQ Resources
  rRabbitPasswordKMSKeyAlias:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/${product}-rabbit-pwd-key
      TargetKeyId: !Ref rRabbitPasswordKMSKey

  rRabbitPasswordKMSKey:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::KMS::Key
    Properties:
      Description: KMS Key for Rabbit Password Secret
      Enabled: !!bool 'true'
      EnableKeyRotation: !!bool 'true'
      KeyPolicy:
        Version: '2012-10-17'
        Id: team-key-default
        Statement:
          - Sid: Enable IAM and allow interactive (human) role(s) key use permissions
            Effect: Allow
            Principal: 
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action:
            - kms:Encrypt
            - kms:Decrypt
            - kms:ReEncrypt*
            - kms:GenerateDataKey*
            - kms:DescribeKey
            - kms:*
            Resource: '*'
            Condition:
              ArnLike:
                aws:PrincipalArn:
                  - !Sub arn:aws:iam::${AWS::AccountId}:role/*
          - Sid: Enable IAM and allow service (non-human) role(s) key use permissions
            Effect: Allow
            Principal:
              AWS: !GetAtt rRabbitConfigureRole.Arn
            Action:
            - kms:Encrypt
            - kms:Decrypt
            - kms:ReEncrypt*
            - kms:GenerateDataKey*
            - kms:DescribeKey
            Resource: '*'
            Condition:
              'Null':
                kms:ViaService: !!bool 'false'
              ArnLike:
                aws:PrincipalArn:
                  - Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/*
          - Sid: Allow service (non-human) role(s) grant operations on CMK
            Effect: Allow
            Principal: 
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:role/cloudformationservicerole
            Action:
            - kms:CreateGrant
            - kms:ListGrants
            - kms:RetireGrant
            - kms:RevokeGrant
            - kms:*
            Resource: '*'
            Condition:
              Bool:
                kms:GrantIsForAWSResource: !!bool 'true'
              StringEquals:
                aws:PrincipalAccount: !Ref AWS::AccountId
      PendingWindowInDays: !!int '30'

  rRabbitPasswordSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${product}-secret-${env}-rabbitpwd
      Description: The password for the rabbit-admin user in RabbitMQ
      KmsKeyId: !Ref rRabbitPasswordKMSKey
      GenerateSecretString:
        PasswordLength: 15
        ExcludeCharacters: ',:='

  rRabbitUserPasswordKMSKeyAlias:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/${product}-rabbit-user-pwd-key
      TargetKeyId: !Ref rRabbitUserPasswordKMSKey

  rRabbitUserPasswordKMSKey:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::KMS::Key
    Properties:
      Description: KMS Key for Rabbit User Password Secret
      Enabled: !!bool 'true'
      EnableKeyRotation: !!bool 'true'
      KeyPolicy:
        Version: '2012-10-17'
        Id: team-key-default
        Statement:
          - Sid: Enable IAM and allow interactive (human) role(s) key use permissions
            Effect: Allow
            Principal: 
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action:
            - kms:Encrypt
            - kms:Decrypt
            - kms:ReEncrypt*
            - kms:GenerateDataKey*
            - kms:DescribeKey
            - kms:*
            Resource: '*'
            Condition:
              ArnLike:
                aws:PrincipalArn:
                  - !Sub arn:aws:iam::${AWS::AccountId}:role/*
          - Sid: Enable IAM and allow service (non-human) role(s) key use permissions
            Effect: Allow
            Principal:
              AWS: !GetAtt rRabbitConfigureRole.Arn
            Action:
            - kms:Encrypt
            - kms:Decrypt
            - kms:ReEncrypt*
            - kms:GenerateDataKey*
            - kms:DescribeKey
            Resource: '*'
            Condition:
              'Null':
                kms:ViaService: !!bool 'false'
              ArnLike:
                aws:PrincipalArn:
                  - Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/*
          - Sid: Allow service (non-human) role(s) grant operations on CMK
            Effect: Allow
            Principal: 
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:role/cloudformationservicerole
            Action:
            - kms:CreateGrant
            - kms:ListGrants
            - kms:RetireGrant
            - kms:RevokeGrant
            - kms:*
            Resource: '*'
            Condition:
              Bool:
                kms:GrantIsForAWSResource: !!bool 'true'
              StringEquals:
                aws:PrincipalAccount: !Ref AWS::AccountId
      PendingWindowInDays: !!int '30'

  rRabbituserPasswordSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${product}-secret-${env}-rabbituserpwd
      Description: The password for the app-app user in RabbitMQ
      KmsKeyId: !Ref rRabbitUserPasswordKMSKey
      GenerateSecretString:
        PasswordLength: 15
        ExcludeCharacters: ',:='

  rRabbitMQClusterSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${product}-secgroup
      VpcId: !Ref VPCId
      GroupDescription: Enable RabbitMQ Access within SecGroup
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 127.0.0.1/32
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 10.0.0.0/16
      SecurityGroupIngress:
        - CidrIp: "0.0.0.0/0"
          IpProtocol: "-1"
        - IpProtocol: tcp
          CidrIp: !Ref AppSubnetCIDR1
          FromPort: 5671
          ToPort: 5671
          Description: Allowing inbound from App Subnet1
        - IpProtocol: tcp
          CidrIp: !Ref AppSubnetCIDR1
          FromPort: 443
          ToPort: 443
          Description: Allowing inbound from App Subnet1
      Tags:
        - Key: Name
          Value: !Sub ${product}-secgroup-${env}-rabbitcluster
        - Key: team:lifecycle
          Value: !Ref env
        - Key: team:vsad
          Value: !Ref pVsadTag
        - Key: team:vast
          Value: !Ref pVastTag
        - Key: team:purpose
          Value: Security Group for RabbitMQ cluster
        - Key: team:dataclass
          Value: !Ref TagteamDataclass
        - Key: team:launched-by
          Value: !Ref pTagteamLaunchedBy
        - Key: team:resource-custodian
          Value: !Ref pTagteamResourceCustodian
        - Key: team:team-owner
          Value: !Ref TagteamTeamOwner
  
  rRabbitMQInternalEgress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref rRabbitMQClusterSecurityGroup
      IpProtocol: '-1'
      DestinationSecurityGroupId: !Ref rRabbitMQClusterSecurityGroup

  rRabbitBroker:
    #Condition: cIsR2ActiveOrIsMain
    Type: AWS::AmazonMQ::Broker
    Properties:
      AutoMinorVersionUpgrade: false # @Product Team
      BrokerName: !Sub ${product}-mqbroker-${env}-rabbitmq-1
      DeploymentMode: SINGLE_INSTANCE
                          
      EngineType: RABBITMQ
      EngineVersion: 3.9.13
      
      HostInstanceType: mq.m5.large
      Logs:
        General: true
      MaintenanceWindowStartTime: # Team
        DayOfWeek: Monday
        TimeOfDay: "00:00"
        TimeZone: America/Chicago
      PubliclyAccessible: false
      SecurityGroups: [!Ref rRabbitMQClusterSecurityGroup]
      SubnetIds: 
        - !Ref AppSubnet1
      Users: 
        - 
          Password: !Sub '{{resolve:secretsmanager:${rRabbitPasswordSecret}:SecretString}}'
          Username: !Ref AdminUsername

      Tags:
        - Key: Name
          Value: !Sub ${product}-mqbroker-${env}-rabbitcluster

    
  rRabbitConfigureFunction:
    #Condition: cIsMainRegion
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${product}-lambda-${env}-configure-rabbit
      CodeUri:
        Bucket: !Ref LambdaCodeBucket
        Key: my-app/RabbitLambda.zip
        Version: !Ref ObjectVersion
      Environment:
        Variables:
          SECRET_ARN: !Ref rRabbitPasswordSecret
          RABBIT_ENDPOINT: !Sub ${rRabbitBroker}.mq.${AWS::Region}.amazonaws.com
          ENVIRONMENT: dev
      PackageType: Zip
      VpcConfig:
        SecurityGroupIds:
          - !Ref rRabbitMQClusterSecurityGroup
        SubnetIds:
          - !Ref AppSubnet1
      Handler: app.handler
      Role: !GetAtt rRabbitConfigureRole.Arn
      Runtime: python3.9
      Timeout: 30
  
  rRabbitConfigureCustomResource:
    #Condition: cIsMainRegion
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !GetAtt rRabbitConfigureFunction.Arn
      Version: 2 # Increment this when you need the code to be run again

  rRabbitConfigureRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: rabbitmq-configure-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      # PermissionsBoundary: !Sub arn:aws:iam::${AWS::AccountId}:policy/team-fed-svcrole-boundary
      Policies:
        - PolicyName: secretsmanager
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetResourcePolicy
                  - secretsmanager:GetSecretValue
                  - secretsmanager:DescribeSecret
                  - secretsmanager:ListSecretVersionIds
                  - secretsmanager:ListSecrets
                Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:* # !Ref rRabbitPasswordSecret # Manually enter role name as to break circular dependency 
        - PolicyName: allowkmsforsecret
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - kms:*
                Resource: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/*
        - PolicyName: lambdainvpc
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DeleteNetworkInterface
                  - ec2:AssignPrivateIpAddress
                  - ec2:UnassignPrivateIpAddress
                Resource: '*'
